Add freeradius config test
vinted/chef-freeradius pull request #4
Opened 2016-09-22 08:14 UTC by mazeika

Added freeradius config test
@vinted/sre

2016-09-22 08:36 UTC, vdnt commented on metadata.rb
> +version          "1.1.0"
patch level change

2016-09-22 08:36 UTC, vdnt requested changes

2016-09-22 09:58 UTC, mazeika commented on metadata.rb
> +version          "1.1.0"
Fixed.

2016-09-22 09:58 UTC, mazeika commented
fixed
@vinted/sre

2016-09-22 10:02 UTC, vdnt approved these changes

2016-09-26 12:34 UTC, vdnt approved these changes

2016-09-26 13:00 UTC, ernestas-vinted commented on metadata.rb
> -%w{ ubuntu centos debian }.each do |os|
this was in https://github.com/vinted/chef-freeradius/pull/3/files

2016-09-26 13:01 UTC, ernestas-vinted commented
first merge this https://github.com/vinted/chef-freeradius/pull/3/files and rebase on this PR

2016-09-26 13:33 UTC, mazeika commented
Rebased, fixed version
@vinted/sre

2016-09-30 12:30 UTC, benner approved these changes

2016-09-30 12:39 UTC, ernestas-vinted approved these changes

2016-09-30 14:14 UTC, merged